server:
  port: 8080
  
spring:      
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/meeting_room?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimeZone=GMT
      
      username: root  
      password: root
      
  jpa: 
    database: MYSQL 
    show-sql: true  
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect  
